name: Dart CI

on:
  release:
    branches:
      - master
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dart:stable

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Generate code
        run: cd example && dart pub get && dart pub run build_runner build --delete-conflicting-outputs
      - name: Analyze packages
        run: PKGS="example retrofit generator" ./tool/travis.sh dartanalyzer
      - name: Install dependencies
        run: cd generator && dart pub get
      - name: Run tests
        run: |
          cd generator && dart pub run test

      - name: Release new version
        run: |
          cd generator 
          RELEASE=${GITHUB_REF##*/}
          sed -i -e "s/version:.*/version: $RELEASE/g" pubspec.yaml

      - name: '>> Publish package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          force: true
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
